name: nemid_auth
description: A Flutter plugin to integrate the nemid libraries for iOS and Android.
version: 1.0.1
homepage: https://github.com/thongdinh/flutter_nemid_auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.tsdev.nemidauth
        pluginClass: NemIdPlugin
      ios:
        pluginClass: NemIdPlugin
